WIP Issue #52 - Documentation changes
ggciag/mandyoc pull request #56
Opened 2022-02-08 19:30 UTC by jamisonassuncao

Changed incorrect image; 
Changed param.txt file in the documentation (parameter file section);
Changed van Keken's Python script to create proper param.txt file (just to fit new param.txtx changes, nothing big).

2022-02-10 18:00 UTC, victorsacek commented on docs/files/src/param.txt
> +multigrid                           = 1             # ok -> soon to be on the command line only
```suggestion

```

2022-02-22 23:14 UTC, jamisonassuncao commented on docs/files/src/param.txt
>  particles_perturb_factor            = 0.0           # default is 0.5 [values are between 0 and 1]
@victorsacek Can you add a description to this parameter? I think we missed it during the discussion

2022-02-22 23:15 UTC, jamisonassuncao commented on docs/files/parameter-file.rst
> +        definition: default is 0.5
@victorsacek Can you add a description to this parameter? I think we missed it during the discussion

2022-03-09 20:53 UTC, victorsacek requested changes

2022-03-09 20:55 UTC, jamisonassuncao commented on docs/files/parameter-file.rst
> +        definition: default is 0.5
``
```suggestion
        definition: indicates the amount of perturbation of the initial location of the particles relative to a regular grid distribution. 
```

2022-03-09 21:48 UTC, merged