WIP - Create the jupyter notebook for the examples
ggciag/mandyoc pull request #58
Opened 2022-02-14 20:34 UTC by aguspesce

I'm making a Jupyter notebook for each of the examples.
Each notebook generates the input files, gives instructions to run the model using Mandyoc, and plots the results.

I am taking into account the comments of the reviewer:

- [ ] Please consider merging README markdown files and PYTHON scripts into a Jupyter notebook. They are easier to read, especially on GitHub. You can also take the user through the step of installing the required Python dependencies...
- [ ] - Please don't expect user to have PETSc installed in their HOME directory as default...
- [ ] - Jupyter notebooks would also help to visualize the outcome of the models / Benchmarks. As it is now, users must run the model themselves to see the result and they don't have a mean of comparison. That is also where you should compare with other codes (I2VES, UNDERWORLD, STAGYY)

Fix #47

2022-03-08 19:56 UTC, aguspesce commented
@jamisonassuncao, @victorsacek, @rafaelmds,
I've finished passing all the script in a Jupyter notebook.  Can you give them a reviewer?

2022-03-08 20:27 UTC, rafaelmds commented
@aguspesce We will close JOSS issues manually. Could you change "fix" to something like "addresses".

2022-03-08 20:36 UTC, rafaelmds commented
- remove white space in file name [comparing plot_max_surface.ipynb](https://github.com/ggciag/mandyoc/pull/58/files#diff-0252c355e0522d172d413fd8dc6989dc875f91608a45c67006ae1aed6aef3c75)

2022-03-08 20:43 UTC, rafaelmds requested changes

2022-03-08 20:43 UTC, rafaelmds commented on examples/Crameri2012_case2/comparing plot_max_surface.ipynb
> +    "        \n",
```suggestion
    "\n",
    "arg_sorted = np.argsort(times)\n",
    "times = times[arg_sorted]\n",
    "surface_topo_mandyoc = surface_topo_mandyoc[arg_sorted]\n",
    "\n",
```

surface_filenames are not being sorted correctly. This fix ordering to plot points in the correct order (time ordered).

2022-03-09 11:30 UTC, rafaelmds approved these changes

2022-03-09 17:53 UTC, aguspesce commented
@victorsacek: I fixed the suggestion you sent me by mail

2022-03-09 17:57 UTC, merged